apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: grpc-demo-route-istio
metadata:
  annotations:
    description: A group of interconnected GRPC demo services written in Go that run on OpenShift Service Mesh.
    iconClass: icon-go-gopher
    openshift.io/display-name: Interconnected GRPC demo services running on OpenShift Service Mesh.
    openshift.io/documentation-url: https://github.com/drhelius/grpc-demo
    openshift.io/provider-display-name: Ignacio Sánchez
    openshift.io/support-url: https://twitter.com/drhelius
    tags: go,grpc,demo,service,istio
  labels:
    template: grpc-demo-route
  name: grpc-demo-route-istio
objects:

##################################################################################################
# Route
##################################################################################################

- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: ${GRPC_ROUTE_NAME}
  spec:
    host: ${GRPC_ROUTE}
    to:
      kind: Service
      name: istio-ingressgateway
      weight: 100
    port:
      targetPort: http2
    tls:
      termination: edge

###############################################################################
# Parameters
###############################################################################

parameters:

- description: Route URL for external access to the GRPC service
  name: GRPC_ROUTE
  displayName: Route URL for external access to the GRPC service
  required: true
- description: Name of the route for external access to the GRPC service
  name: GRPC_ROUTE_NAME
  displayName: Name of the route for external access to the GRPC service
  required: true
