---
# Grants all authenticated users the read permissions for trace data.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tempostack-traces-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tempostack-traces-writer-dev
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: otel
  # - kind: Group
  #   apiGroup: rbac.authorization.k8s.io
  #   name: system:authenticated