apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: 00-jump-app-config
objects:
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: back-golang
  spec:
    gateways:
    - back-golang
    - mesh
    hosts:
    - back-golang-${USER_NAMESPACE}.${OCP_APPS_DOMAIN}
    - back-golang.${USER_NAMESPACE}.svc.cluster.local
    - back-golang
    http:
    - fault:
        delay:
          fixedDelay: 2s
          percentage:
            value: 100
      route:
        - destination:
            host: back-golang.${USER_NAMESPACE}.svc.cluster.local
            subset: v1
          weight: 100
parameters:
  - description: Tutorial User Namespace
    displayName: Tutorial User Namespace
    name: USER_NAMESPACE
    required: true
  - description: Openshift Apps Domain
    displayName: Openshift Apps Domain
    name: OCP_APPS_DOMAIN
    required: true