apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: jump-app-template
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: back-golang
        version: v1
      name: back-golang-v1
    spec:
      ports:
        - name: http-8442
          port: 8442
          protocol: 
          targetPort: 8442   
      selector:
        app: back-golang
        version: v1
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: back-python
        version: v1
      name: back-python-v1
    spec:
      ports:
        - name: http-8080
          port: 8444
          protocol: 
          targetPort: 8080   
      selector:
        app: back-python
        version: v1
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: back-springboot
        version: v1
      name: back-springboot-v1
    spec:
      ports:
        - name: http-8080
          port: 8080
          protocol: 
          targetPort: 8080
        - name: http-8443
          port: 8443
          protocol: 
          targetPort: 8443
        - name: http-8778
          port: 8778
          protocol: 
          targetPort: 8778   
      selector:
        app: back-springboot
        version: v1
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: front-javascript
        version: v1
      name: front-javascript-v1
    spec:
      ports:
        - name: http-8080
          port: 8080
          protocol: 
          targetPort: 3000   
      selector:
        app: front-javascript
        version: v1
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: back-golang
        version: v1
      name: back-golang-v1
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: back-golang
      template:
        metadata:
          labels:
            name: back-golang-v1
            app: back-golang
            version: v1
        spec:
          containers:
          - image: image-registry.openshift-image-registry.svc:5000/jump-app-cicd/back-golang:develop
            imagePullPolicy: Always
            name: back-golang-v1
            ports:
              - containerPort: 8442
                protocol: TCP
            resources: {}
            env:  
              - name: APP_REF_NAME
                value: jump-app
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: back-python
        version: v1
      name: back-python-v1
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: back-python
      template:
        metadata:
          labels:
            name: back-python-v1
            app: back-python
            version: v1
        spec:
          containers:
          - image: image-registry.openshift-image-registry.svc:5000/jump-app-cicd/back-python:develop
            imagePullPolicy: Always
            name: back-python-v1
            ports:
              - containerPort: 8080
                protocol: TCP
            resources: {}
            env:  
              - name: APP_REF_NAME
                value: jump-app
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: back-springboot
        version: v1
      name: back-springboot-v1
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: back-springboot
      template:
        metadata:
          labels:
            name: back-springboot-v1
            app: back-springboot
            version: v1
        spec:
          containers:
          - image: image-registry.openshift-image-registry.svc:5000/jump-app-cicd/back-springboot:develop
            imagePullPolicy: Always
            name: back-springboot-v1
            ports:
              - containerPort: 8080
                protocol: TCP
              - containerPort: 8443
                protocol: TCP
              - containerPort: 8778
                protocol: TCP
            resources: {}
            env:  
              - name: APP_REF_NAME
                value: jump-app
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: front-javascript
        version: v1
      name: front-javascript-v1
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: front-javascript
      template:
        metadata:
          labels:
            name: front-javascript-v1
            app: front-javascript
            version: v1
        spec:
          containers:
          - image: image-registry.openshift-image-registry.svc:5000/jump-app-cicd/front-javascript:develop
            imagePullPolicy: Always
            name: front-javascript-v1
            ports:
              - containerPort: 3000
                protocol: TCP
            resources: {}
            env:  
              - name: APP_REF_NAME
                value: jump-app
              - name: REACT_APP_BACK
                value: https://back-golang-${USER_NAMESPACE}.${OCP_APPS_DOMAIN}/jump
              - name: REACT_APP_GOLANG
                value: http://back-golang-v1:8442
              - name: REACT_APP_SPRINGBOOT
                value: http://back-springboot-v1:8443
              - name: REACT_APP_PYTHON
                value: http://back-python-v1:8444
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: back-golang
    spec:
      to:
        kind: Service
        name: back-golang-v1
      port:
        targetPort: http-8442
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: front-javascript
    spec:
      to:
        kind: Service
        name: front-javascript-v1
      port:
        targetPort: http-8080
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
parameters:
  - description: Tutorial User Namespace
    displayName: Tutorial User Namespace
    name: USER_NAMESPACE
    required: true
  - description: Openshift Apps Domain
    displayName: Openshift Apps Domain
    name: OCP_APPS_DOMAIN
    required: true
