apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  # ClusterWide | Multitenant
  mode: ClusterWide
  security:
    controlPlane:
      mtls: false
    dataPlane:
      automtls: false
      mtls: false
  tracing:
    sampling: 10000
    type: Jaeger
  profiles:
    - default
  gateways:
    ingress:
      runtime:
        deployment:
          autoScaling:
            enabled: false
          replicas: 1
          strategy:
            rollingUpdate:
              maxSurge: "1"
              maxUnavailable: "0"
            type: RollingUpdate
    egress:
      runtime:
        deployment:
          autoScaling:
            enabled: false
          replicas: 1
    openshiftRoute:
      enabled: false
  policy:
    type: Istiod

  addons:
    grafana:
      enabled: true
    kiali:
      enabled: true
      name: kiali
    jaeger:
      install:
        storage:
          type: Memory
    prometheus:
      enabled: true
  telemetry:
    type: Istiod
  version: v2.6
  proxy:
    logging:
      level: info
    networking:
      trafficControl:
        inbound: {}
        outbound:
          policy: REGISTRY_ONLY # Only external services can be reached if a Service Entry object is created
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 128Mi
  runtime:
    components:
      pilot:
        container:
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 128Mi
        deployment:
          autoScaling:
            enabled: false
          replicas: 1


# EOF