apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  # a list of projects joined into the service mesh
  # members:
  #   - user01-mesh
  #   - user02-mesh
  memberSelectors:
  - matchLabels:
      istio-injection: enabled