apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: 03-istio-system-dr
objects:
  - apiVersion: networking.istio.io/v1alpha3
    kind: DestinationRule
    metadata:
      name: originate-mtls-for-nginx-${USER_NAMESPACE}
    spec:
      host: my-nginx.${USER_NAMESPACE}-mesh-external.svc.cluster.local
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
        portLevelSettings:
        - port:
            number: 443
          tls:
            mode: MUTUAL
            credentialName: ${USER_NAMESPACE}-mesh-external-egress-nginx-client-certs
            sni: my-nginx.${USER_NAMESPACE}-mesh-external.svc.cluster.local
  - apiVersion: networking.istio.io/v1alpha3
    kind: ServiceEntry
    metadata:
      name: nginx-${USER_NAMESPACE}
    spec:
      hosts:
      - my-nginx.${USER_NAMESPACE}-mesh-external.svc.cluster.local
      ports:
      - number: 80
        name: http
        protocol: HTTP
      - number: 443
        name: https
        protocol: HTTPS
      resolution: DNS
      endpoints:
      - address: my-nginx.${USER_NAMESPACE}-mesh-external.svc.cluster.local
        ports:
          https: 443
parameters:
  - description: Tutorial User Namespace
    displayName: Tutorial User Namespace
    name: USER_NAMESPACE
    required: true
  - description: Openshift Apps Domain
    displayName: Openshift Apps Domain
    name: OCP_APPS_DOMAIN
    required: true
