apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: jump-app-front-gw-template
objects:
  - apiVersion: maistra.io/v1
    kind: ServiceMeshMember
    metadata:
      name: default
    spec:
      controlPlaneRef:
        name: basic
        namespace: istio-system
