apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: jump-app-gws-template
objects:
  - apiVersion: security.istio.io/v1beta1
    kind: PeerAuthentication
    metadata:
      name: default
    spec:
      mtls:
        mode: STRICT
  - apiVersion: networking.istio.io/v1alpha3
    kind: DestinationRule
    metadata:
      name: ${USER_NAMESPACE}-mtls
    spec:
      host: "*.${USER_NAMESPACE}.svc.cluster.local"
      trafficPolicy:
        tls:
          mode: ISTIO_MUTUAL
parameters:
  - description: Tutorial User Namespace
    displayName: Tutorial User Namespace
    name: USER_NAMESPACE
    required: true
  - description: Openshift Apps Domain
    displayName: Openshift Apps Domain
    name: OCP_APPS_DOMAIN
    required: true