apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: 00-jump-app-gws
objects:
  - apiVersion: networking.istio.io/v1alpha3
    kind: Gateway
    metadata:
      name: back-golang
    spec:
      selector:
        istio: ingressgateway
      servers:
        - port:
            number: 80
            name: http
            protocol: HTTP
          hosts:
          - back-golang-${USER_NAMESPACE}.${OCP_APPS_DOMAIN}
  - apiVersion: networking.istio.io/v1alpha3
    kind: Gateway
    metadata:
      name: front-javascript
    spec:
      selector:
        istio: ingressgateway
      servers:
        - port:
            number: 80
            name: http
            protocol: HTTP
          hosts:
          - front-javascript-${USER_NAMESPACE}.${OCP_APPS_DOMAIN}
parameters:
  - description: Tutorial User Namespace
    displayName: Tutorial User Namespace
    name: USER_NAMESPACE
    required: true
  - description: Openshift Apps Domain
    displayName: Openshift Apps Domain
    name: OCP_APPS_DOMAIN
    required: true