apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempostack-traces-reader-dev
rules:
  - apiGroups:
      - 'tempo.grafana.com'
    # Lists of tenants (dev, prod, etc.) that can be used to filter the traces
    resources:
      - dev
    resourceNames:
      - traces
    verbs:
      - 'get'